# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Kinvolk docs Hugo theme"
license = "Apache 2.0"
description = "Documentation and basic pages"
homepage = "https://kinvolk.io"
tags = ["project", "documentation"]
features = ["", ""]
min_version = 0.36

[author]
  name = "Kinvolk"
  homepage = "https://kinvolk.io"
